[package]
name = "vlrrandom"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
rand = "0.9.0"
axum = "0.8.3"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }